spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: j123
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Taipei&Encoding=utf-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.yucheng: debug